name: Run Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Swift Package Tests
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      # Run tests in Shared
      - name: Run tests in Shared package
        run: swift test --parallel
        working-directory: Shared

      # Run tests in Features
      - name: Run tests in Features package
        run: swift test --parallel
        working-directory: Features